### ISSUE TITLE
Transform flow test failing when running on k8s on Azure.

### ISSUE THREAD

**Issue by sharkinsspatial** [pangeo-forge/pangeo-forge-azure-bakery#4] opened 2021-05-11 01:07 UTC
When trying to reproduce the testing Prefect [flow](https://github.com/pangeo-forge/pangeo-forge-aws-bakery/blob/main/flow_test/transform_flow.py) used while developing `pangeo-forge-aws-bakery` we are encountering an error when running `ds.to_zarr` https://github.com/pangeo-forge/pangeo-forge-azure-bakery/blob/add-k8s-cluster/flow_test/transform_tasks/xarray.py#L30.
```
Traceback (most recent call last):
  File "/Users/ciaran/dev/pangeo-forge-azure-bakery/flow_test/transform_tasks/xarray.py", line 30, in combine_and_write
  File "/usr/local/lib/python3.8/site-packages/xarray/core/dataset.py", line 1907, in to_zarr
    return to_zarr(
  File "/usr/local/lib/python3.8/site-packages/xarray/backends/api.py", line 1454, in to_zarr
    dump_to_store(dataset, zstore, writer, encoding=encoding)
  File "/usr/local/lib/python3.8/site-packages/xarray/backends/api.py", line 1130, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/usr/local/lib/python3.8/site-packages/xarray/backends/zarr.py", line 465, in store
    ds = open_zarr(self.ds.store, group=self.ds.path, chunks=None)
  File "/usr/local/lib/python3.8/site-packages/xarray/backends/zarr.py", line 688, in open_zarr
    ds = open_dataset(
  File "/usr/local/lib/python3.8/site-packages/xarray/backends/api.py", line 501, in open_dataset
    backend_ds = backend.open_dataset(
  File "/usr/local/lib/python3.8/site-packages/xarray/backends/zarr.py", line 749, in open_dataset
    ds = store_entrypoint.open_dataset(
  File "/usr/local/lib/python3.8/site-packages/xarray/backends/store.py", line 37, in open_dataset
    ds = Dataset(vars, attrs=attrs)
  File "/usr/local/lib/python3.8/site-packages/xarray/core/dataset.py", line 741, in __init__
    variables, coord_names, dims, indexes, _ = merge_data_and_coords(
  File "/usr/local/lib/python3.8/site-packages/xarray/core/merge.py", line 477, in merge_data_and_coords
    return merge_core(
  File "/usr/local/lib/python3.8/site-packages/xarray/core/merge.py", line 631, in merge_core
    dims = calculate_dimensions(variables)
  File "/usr/local/lib/python3.8/site-packages/xarray/core/dataset.py", line 203, in calculate_dimensions
    raise ValueError(
ValueError: conflicting sizes for dimension 'time': length 20 on 'time' and length 15 on 'anom'
```

@TomAugspurger any suggestions you might have for diagnosing if this might be related to our configuration of Azure Blob storage would be super appreciated 🙇 .

**Comment by ciaranevans** [comment] 2021-05-11 15:34
From what I could see, the buckets looked fine, here's a screenshot:

![image](https://user-images.githubusercontent.com/9111975/117843493-c3745c00-b276-11eb-90ce-5ffc45a2d2aa.png)

This is from a past convo with Sean, but I'll run it again and send a current look

**Comment by ciaranevans** [comment] 2021-05-11 15:54
The mystery continues 🕵️‍♀️

Images of storage **before**:

![image](https://user-images.githubusercontent.com/9111975/117846545-73e35f80-b279-11eb-992c-46ae195cb897.png)
![image](https://user-images.githubusercontent.com/9111975/117846559-76de5000-b279-11eb-930d-56bdd277198b.png)

Images of storage **after**:

![image](https://user-images.githubusercontent.com/9111975/117846600-82ca1200-b279-11eb-9685-2e0345eef209.png)
![image](https://user-images.githubusercontent.com/9111975/117846620-85c50280-b279-11eb-980a-584416103813.png)
![image](https://user-images.githubusercontent.com/9111975/117846649-8bbae380-b279-11eb-9220-e496eabecfc4.png)
![image](https://user-images.githubusercontent.com/9111975/117846661-8d84a700-b279-11eb-8854-c40a85a537d7.png)

**Comment by ciaranevans** [comment] 2021-05-12 16:21
@TomAugspurger I'm going to spend tomorrow fully fleshing out a run through of exactly what I'm doing, running, and seeing, I'll be dumping all the logs I can too

**Comment by ciaranevans** [comment] 2021-05-13 12:16
@TomAugspurger @martindurant @sharkinsspatial 

Hey folks, here's a full rundown of what I'm doing to get this flow to break, what is left in Azure after each flow run and what logs I can get out of Prefect & K8s

# High level overview

Whilst trying to confirm that the Azure Bakery is deployed/setup correctly, we've been trying to run `flow_test/transform_flow.py` which is a copy of the same flow from the AWS Bakery [here](https://github.com/pangeo-forge/pangeo-forge-aws-bakery/blob/main/flow_test/transform_flow.py). The modifications made are:

* Removal of all the ECS/Dask setup
* Switch from `s3://` to `abfs`
* Addition of a `try/except` block in `flow_tests/transform_tasks/xarray.py::combine_and_write`

## Combine and Write try/except

In the AWS Bakery, this function looks like:

```python
@task
def combine_and_write(
    sources: List[str], target: str, append_dim: str, concat_dim: str
) -> List[str]:
    double_open_files = [fsspec.open(url).open() for url in sources]
    ds = xr.open_mfdataset(double_open_files, combine="nested", concat_dim=concat_dim)
    ds = ds.chunk({append_dim: len(sources)})
    mapper = fsspec.get_mapper(target)

    if not len(mapper):
        kwargs = dict(mode="w")
    else:
        kwargs = dict(mode="a", append_dim=append_dim)
    ds.to_zarr(mapper, **kwargs)
    return target
```

This function currently fails in the Azure Bakery, because of this and because of a current 'bug' in Prefect, we don't get a chance for the Dask logs to be collected by Prefect. To get around this, I've wrapped the functionality in a `try/except` block. When the exception is raised, I log out the error and grossly whack a 60s `time.sleep` which gives Prefect a chance to log out the errors to the UI.

The modified function in the Azure Bakery looks like:

```python
@task
def combine_and_write(
    sources: List[str], target: str, append_dim: str, concat_dim: str
) -> List[str]:
    try:
        double_open_files = [fsspec.open(url).open() for url in sources]
        ds = xr.open_mfdataset(double_open_files, combine="nested", concat_dim=concat_dim)
        ds = ds.chunk({append_dim: len(sources)})
        mapper = fsspec.get_mapper(target)

        if not len(mapper):
            kwargs = dict(mode="w")
        else:
            kwargs = dict(mode="a", append_dim=append_dim)
        ds.to_zarr(mapper, **kwargs)
        return target
    except Exception as ex:
        logger = prefect.context.get("logger")
        logger.info(ex)
        logger.info(traceback.format_exc())
        import time
        time.sleep(60)
        raise ex
```

# Methods of displaying the failure

My method of displaying the failures we're seeing will be 2 flavours:

* [**Method One**](#method-one) which registers the flow, invokes it, then deletes all generated data (Prefect Results, Flow artifacts) - This will be done 3 times (I.E 3 clean runs in succession)
* [**Method Two**](#method-two) which registers the flow, invokes it but doesn't delete any generated data - This will be done 3 times (I.E 3 over the top runs in succession)

I'll deploy and destroy the Bakery for each Method, so I know it's not tainting the methods.

For each method, I'll provide the container logs of the Dask Workers, Prefect Logs, and a `.zip` of the Storage container per run

For each Flow run, I click the **🚀 Run** button on the Prefect UI on the homepage of the current Flow version, on the Run configuration page, I click the **Run 🚀** button without modifying the parameters

To get the Dask Worker logs, I run the following query in Azure Logs Analytics:

```kql
let container_ids = toscalar(KubePodInventory
| where ContainerCreationTimeStamp >= datetime(<time just before the flow run>)
| extend labels = todynamic(PodLabel)[0]
| where labels.flow contains "dask-transform-flow" and labels["dask.org/component"] contains "worker"
| project PodUid, ContainerID
| distinct PodUid, ContainerID
| summarize make_set(ContainerID));
ContainerLog
| where (container_ids) contains ContainerID
| order by ContainerID, TimeGenerated
| project ContainerID, TimeGenerated, LogEntry
```

This provides me with results for all Dask `worker` containers from when I ran the Flow, the results are rows of `ContainerID`, `TimeGenerated`, and the actual `LogEntry` - There should be 2 containers in each results dump, this is just what I've observed gets spun up

# Method One

## Bakery Deployment

I deploy the Bakery with:

```bash
$ make deploy-bakery
```

## Flow registration

I registered the Flow with:

```bash
$ poetry run dotenv run python3 flow_test/transform_flow.py
[2021-05-13 11:04:12+0100] INFO - prefect.Azure | Uploading dask-transform-flow/2021-05-13t10-04-12-300682-00-00 to ciarandev-bakery-flow-storage-container
Flow URL: https://cloud.prefect.io/ciaran-developmentseed-account/flow/a4d1db1c-fd98-4e5e-a7c1-6dab7ce2adac
 └── ID: 1b5ef992-c210-4634-8cd0-81e977f181c8
 └── Project: CiaransTestProject
 └── Labels: ['ciarandev']
```

_Apologies for the verbose command, one downside of Poetry is no native `.env` support, hence the `dotenv run`_

## Post Registration Storage Container contents

The zip of the Storage Container contents can be found [here](https://drive.google.com/file/d/1MtC9K3xwX8CAz6C2VZcd1cqDbVmtgKB6/view?usp=sharing)

## Flow Run 1

The zip of the Dask worker logs, Prefect logs, and Storage Container contents can be found [here](https://drive.google.com/file/d/1vAEOgl4OsWvvDvDNbUlVvc07T9dwLh--/view?usp=sharing)

## Flow Run 2

The zip of the Dask worker logs, Prefect logs, and Storage Container contents can be found [here](https://drive.google.com/file/d/1Y2jaj2u3fFZ27wkSfNDZt1CQYiaIsrtf/view?usp=sharing)

## Flow Run 3

The zip of the Dask worker logs, Prefect logs, and Storage Container contents can be found [here](https://drive.google.com/file/d/1ztLLST-sj8NUWIggmICciWvGa55Rjy3B/view?usp=sharing)

# Method Two

## Bakery Deployment

I deploy the Bakery with:

```bash
$ make deploy-bakery
```

## Flow registration

I registered the Flow with:

```bash
$ poetry run dotenv run python3 flow_test/transform_flow.py
[2021-05-13 12:37:34+0100] INFO - prefect.Azure | Uploading dask-transform-flow/2021-05-13t11-37-34-683803-00-00 to ciarandev-bakery-flow-storage-container
Flow URL: https://cloud.prefect.io/ciaran-developmentseed-account/flow/a4d1db1c-fd98-4e5e-a7c1-6dab7ce2adac
 └── ID: c6ae8bca-2a96-40b6-976b-f0531af10c40
 └── Project: CiaransTestProject
 └── Labels: ['ciarandev']
```

_Apologies for the verbose command, one downside of Poetry is no native `.env` support, hence the `dotenv run`_

## Post Registration Storage Container contents

The zip of the Storage Container contents can be found [here](https://drive.google.com/file/d/1cz8uufN_DeFOUG73qcMZDxYVv6vsHWNv/view?usp=sharing)

## Flow Run 1

The zip of the Dask worker logs, Prefect logs, and Storage Container contents can be found [here](https://drive.google.com/file/d/1lGfOi0uU23whm-0xgsOGeeeJdOqZER0V/view?usp=sharing)

## Flow Run 2

The zip of the Dask worker logs, Prefect logs, and Storage Container contents can be found [here](https://drive.google.com/file/d/1MmlgUEn1rWhWuXcSik1vgZLD9poKEoGj/view?usp=sharing)

## Flow Run 3

The zip of the <s>Dask worker logs</s>, Prefect logs, and Storage Container contents can be found [here](https://drive.google.com/file/d/1y0CNhRhz7lYq9qm1S2TzXpUlA5UCdnhT/view?usp=sharing)

**Note** The Pod didn't seem to log out this time around, though nothing changed so I can't include the logs. For this reason, I'll do a 4th run and see what happens

## Flow Run 4

The zip of the Dask worker logs, Prefect Flow container logs, Prefect logs, and Storage Container contents can be found [here](https://drive.google.com/file/d/1-6ZSXsextYErd8AfFwmlMgVTVYk7DRNc/view?usp=sharing)

# Summary

It's _really_ hard to pin down what goes wrong here. Mainly because an error causes the containers to get shutdown so most of the error messages are actually do with the shutdown rather than what went wrong.

Hopefully everything I've included will help... Really appreciate any insight folks have as I'm pretty lost at this point!

**Comment by TomAugspurger** [comment] 2021-05-13 13:04
Glancing at the worker logs, this stands out:

```
distributed.comm.utils - ERROR - ('Could not serialize object of type ImplicitToExplicitIndexingAdapter.', "ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyIndexedArray(array=_ElementwiseFunctionArray(_ElementwiseFunctionArray(LazilyIndexedArray(array=<xarray.backends.h5netcdf_.H5NetCDFArrayWrapper object at 0x7f2dd4b575e0>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None), slice(None, None, None)))), func=functools.partial(<function _apply_mask at 0x7f2dddc2f790>, encoded_fill_values={-999}, decoded_fill_value=nan, dtype=dtype('float32')), dtype=dtype('float32')), func=functools.partial(<function _scale_offset_decoding at 0x7f2dddc2f820>, scale_factor=0.009999999776482582, add_offset=0.0, dtype=<class 'numpy.float32'>), dtype=dtype('float32')), key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None), slice(None, None, None))))))")
```

which looks like https://github.com/pydata/xarray/issues/4591, supposed to be fixed by https://github.com/intake/filesystem_spec/pull/477.

It's possible that my attempt in https://github.com/pangeo-forge/pangeo-forge-azure-bakery/issues/4#issuecomment-838685195 didn't create a `Client` with multiple processes, which requires calling `cloudpickle.dumps` on the dataset to move it between processes.

**Comment by ciaranevans** [comment] 2021-05-13 13:20
@TomAugspurger could you confirm what versions of packages you've got locally? I'm just going to actually pin `pangeo-forge-recipes` now that there's a recent release, and pin `xarray` and see what happens.

**Comment by TomAugspurger** [comment] 2021-05-13 13:28
Running `pip list` in the docker image I built from the Dockerfile in this repo:

```
Package                              Version
------------------------------------ ---------------------
adal                                 1.2.7
adlfs                                0.7.4
aiohttp                              3.7.4.post0
applicationinsights                  0.11.10
asciitree                            0.3.3
async-timeout                        3.0.1
atlassian-python-api                 3.8.0
attrs                                20.3.0
azure-common                         1.1.27
azure-core                           1.13.0
azure-cosmos                         3.1.2
azure-datalake-store                 0.0.52
azure-graphrbac                      0.61.1
azure-identity                       1.5.0
azure-mgmt-authorization             1.0.0
azure-mgmt-containerregistry         2.8.0
azure-mgmt-core                      1.2.2
azure-mgmt-keyvault                  9.0.0
azure-mgmt-resource                  8.0.1
azure-mgmt-storage                   17.1.0
azure-storage-blob                   12.8.1
azureml-automl-core                  1.0.85.5
azureml-core                         1.0.85.6
azureml-dataprep                     1.1.38
azureml-dataprep-native              13.2.0
azureml-pipeline                     1.0.85
azureml-pipeline-core                1.0.85.1
azureml-pipeline-steps               1.0.85
azureml-sdk                          1.0.85
azureml-telemetry                    1.0.85.2
azureml-train                        1.0.85
azureml-train-automl-client          1.0.85.4
azureml-train-core                   1.0.85
azureml-train-restclients-hyperdrive 1.0.85
backports.tempfile                   1.0
backports.weakref                    1.0.post1
boto3                                1.17.59
botocore                             1.20.59
cachetools                           4.2.2
certifi                              2020.12.5
cffi                                 1.14.5
chardet                              4.0.0
click                                7.1.2
cloudpickle                          1.6.0
contextlib2                          0.6.0.post1
croniter                             0.3.37
cryptography                         3.4.7
dask                                 2021.4.1
dask-kubernetes                      2021.3.0
Deprecated                           1.2.12
distributed                          2021.4.1
distro                               1.5.0
docker                               5.0.0
dotnetcore2                          2.1.20
dulwich                              0.20.21
entrypoints                          0.3
fasteners                            0.16
flake8                               3.7.9
fsspec                               2021.4.0
fusepy                               3.0.1
google-api-core                      1.26.3
google-auth                          1.30.0
google-cloud-core                    1.6.0
google-cloud-storage                 1.38.0
google-crc32c                        1.1.2
google-resumable-media               1.2.0
googleapis-common-protos             1.53.0
h5netcdf                             0.11.0
h5py                                 3.2.1
HeapDict                             1.0.1
idna                                 2.10
isodate                              0.6.0
jeepney                              0.6.0
jmespath                             0.10.0
jsonpickle                           2.0.0
kubernetes                           12.0.1
kubernetes-asyncio                   12.1.0
locket                               0.2.1
marshmallow                          3.11.1
marshmallow-oneofschema              2.1.0
mccabe                               0.6.1
msal                                 1.11.0
msal-extensions                      0.3.0
msgpack                              1.0.2
msrest                               0.6.21
msrestazure                          0.6.4
multidict                            5.1.0
mypy-extensions                      0.4.3
natsort                              7.1.1
ndg-httpsclient                      0.5.1
numcodecs                            0.7.3
numpy                                1.20.2
oauthlib                             3.1.0
packaging                            20.9
pandas                               1.2.4
pangeo-forge-recipes                 0.3.3
partd                                1.2.0
pathspec                             0.8.1
pendulum                             2.1.2
pip                                  21.1.1
portalocker                          1.7.1
prefect                              0.14.17
protobuf                             3.15.8
psutil                               5.8.0
pyasn1                               0.4.8
pyasn1-modules                       0.2.8
pycodestyle                          2.5.0
pycparser                            2.20
pyflakes                             2.1.1
PyGithub                             1.55
PyJWT                                2.0.1
PyNaCl                               1.4.0
pyOpenSSL                            20.0.1
pyparsing                            2.4.7
python-box                           5.3.0
python-dateutil                      2.8.1
python-dotenv                        0.17.0
python-gitlab                        2.7.1
python-slugify                       4.0.1
pytz                                 2021.1
pytzdata                             2020.1
PyYAML                               5.4.1
rechunker                            0.4.2
requests                             2.25.1
requests-oauthlib                    1.3.0
requests-toolbelt                    0.9.1
rsa                                  4.7.2
ruamel.yaml                          0.15.89
s3transfer                           0.4.2
SecretStorage                        3.3.1
setuptools                           56.0.0
six                                  1.15.0
sortedcontainers                     2.3.0
tabulate                             0.8.9
tblib                                1.7.0
text-unidecode                       1.3
toml                                 0.10.2
toolz                                0.11.1
tornado                              6.1
typing-extensions                    3.7.4.3
urllib3                              1.26.4
websocket-client                     0.58.0
wheel                                0.36.2
wrapt                                1.12.1
xarray                               0.18.1.dev6+g6e14df62
yarl                                 1.6.3
zarr                                 2.7.0
zict                                 2.0.0
```

**Comment by ciaranevans** [comment] 2021-05-13 13:31
Hmm interesting. Maybe I was running with the same. I've pinned them specifically now to `pangeo-forge-recipes==0.3.3` - Also I've just picked up `prefect==0.14.19` which has seemingly just been released. We'll see what this does

**Comment by ciaranevans** [comment] 2021-05-13 13:53
Great. Bumping to `0.14.19` breaks because of `click` 🙃

**Comment by ciaranevans** [comment] 2021-05-13 14:28
So with the following versions:

```
adal                                 1.2.7
adlfs                                0.7.5
aiohttp                              3.7.4.post0
applicationinsights                  0.11.10
asciitree                            0.3.3
async-timeout                        3.0.1
attrs                                21.2.0
azure-common                         1.1.27
azure-core                           1.13.0
azure-cosmos                         3.1.2
azure-datalake-store                 0.0.52
azure-graphrbac                      0.61.1
azure-identity                       1.5.0
azure-mgmt-authorization             1.0.0
azure-mgmt-containerregistry         2.8.0
azure-mgmt-core                      1.2.2
azure-mgmt-keyvault                  9.0.0
azure-mgmt-resource                  8.0.1
azure-mgmt-storage                   17.1.0
azure-storage-blob                   12.8.1
azureml-automl-core                  1.0.85.5
azureml-core                         1.0.85.6
azureml-dataprep                     1.1.38
azureml-dataprep-native              13.2.0
azureml-pipeline                     1.0.85
azureml-pipeline-core                1.0.85.1
azureml-pipeline-steps               1.0.85
azureml-sdk                          1.0.85
azureml-telemetry                    1.0.85.2
azureml-train                        1.0.85
azureml-train-automl-client          1.0.85.4
azureml-train-core                   1.0.85
azureml-train-restclients-hyperdrive 1.0.85
backports.tempfile                   1.0
backports.weakref                    1.0.post1
cachetools                           4.2.2
certifi                              2020.12.5
cffi                                 1.14.5
chardet                              4.0.0
click                                7.1.2
cloudpickle                          1.6.0
contextlib2                          0.6.0.post1
croniter                             0.3.37
cryptography                         3.4.7
dask                                 2021.4.1
dask-kubernetes                      2021.3.1
distributed                          2021.4.1
distro                               1.5.0
docker                               5.0.0
dotnetcore2                          2.1.20
entrypoints                          0.3
fasteners                            0.16
flake8                               3.7.9
fsspec                               2021.4.0
fusepy                               3.0.1
google-auth                          1.30.0
h5netcdf                             0.11.0
h5py                                 3.2.1
HeapDict                             1.0.1
idna                                 2.10
isodate                              0.6.0
jeepney                              0.6.0
jmespath                             0.10.0
jsonpickle                           2.0.0
kubernetes                           12.0.1
kubernetes-asyncio                   12.1.0
locket                               0.2.1
marshmallow                          3.12.1
marshmallow-oneofschema              2.1.0
mccabe                               0.6.1
msal                                 1.11.0
msal-extensions                      0.3.0
msgpack                              1.0.2
msrest                               0.6.21
msrestazure                          0.6.4
multidict                            5.1.0
mypy-extensions                      0.4.3
natsort                              7.1.1
ndg-httpsclient                      0.5.1
numcodecs                            0.7.3
numpy                                1.20.3
oauthlib                             3.1.0
pandas                               1.2.4
pangeo-forge-recipes                 0.3.3
partd                                1.2.0
pathspec                             0.8.1
pendulum                             2.1.2
pip                                  21.1.1
portalocker                          1.7.1
prefect                              0.14.19
psutil                               5.8.0
pyasn1                               0.4.8
pyasn1-modules                       0.2.8
pycodestyle                          2.5.0
pycparser                            2.20
pyflakes                             2.1.1
PyJWT                                2.1.0
pyOpenSSL                            20.0.1
python-box                           5.3.0
python-dateutil                      2.8.1
python-dotenv                        0.17.1
python-slugify                       5.0.2
pytz                                 2021.1
pytzdata                             2020.1
PyYAML                               5.4.1
rechunker                            0.4.2
requests                             2.25.1
requests-oauthlib                    1.3.0
rsa                                  4.7.2
ruamel.yaml                          0.15.89
SecretStorage                        3.3.1
setuptools                           56.0.0
six                                  1.16.0
sortedcontainers                     2.3.0
tabulate                             0.8.9
tblib                                1.7.0
text-unidecode                       1.3
toml                                 0.10.2
toolz                                0.11.1
tornado                              6.1
typing-extensions                    3.10.0.0
urllib3                              1.26.4
websocket-client                     0.59.0
wheel                                0.36.2
xarray                               0.18.0
yarl                                 1.6.3
zarr                                 2.7.0
zict                                 2.0.0
```

I get the following logs [here](https://github.com/pangeo-forge/pangeo-forge-azure-bakery/files/6473061/dask-worker-logs.csv)

**Comment by ciaranevans** [comment] 2021-05-13 14:47
@TomAugspurger Looks like even with these updated dependencies, we're still hitting similar issues

**Comment by martindurant** [comment] 2021-05-20 18:41
I see a couple of JSON errors followed by a timeout? I don't have much of an idea of what this might mean. I recently gained Azure credentials, but I've never actually dealt with abfs in any way - I wrote an early version of the adlfs ("legacy") implementation. If you can make a concrete reproducer, I'm sure adlfs would fix things quickly.

**Comment by TomAugspurger** [comment] 2021-05-20 18:45
This JSONDecodeError is one of the issues I was hitting last weekend. Somewhere in adlfs's caches there's a partially written blob (the JSON Zarr metadata). The actual bytes in BlobStorage are fully written, so it probably isn't a flushing issue, just a caching thing.

I spent a couple hours trying to simplify and debug it, but haven't been able to come up with a minimal reproducer.

**Comment by sharkinsspatial** [comment] 2021-05-20 18:57
@TomAugspurger We made a quick attempt with your streamlined `AzureBlobStorageFS` implementation but ran into the fact that it didn't implement `exists` https://github.com/pangeo-forge/pangeo-forge-recipes/blob/master/pangeo_forge_recipes/storage.py#L94.   Not sure if you hit this in your recipe test?

**Comment by TomAugspurger** [comment] 2021-05-20 19:09
Nope, I just implemented the stuff need to get my workflow running.

You could implement it as something like

```python
return path in self.get_mapper()
```

**Comment by TomAugspurger** [comment] 2021-05-20 19:14
Ah, I guess since I didn't implement `__contains__` it would. With `AzureBlobStorageStore.__contains__` as something like `self.container_client.exists(path/to/blob)`, we can use `azure.storage.blob`'s fast prefix matching.

**Comment by ciaranevans** [comment] 2021-05-21 09:59
@TomAugspurger @martindurant @sharkinsspatial so in the spirit of sorting this once and for all - what would our plan of action look like?

I don't really feel comfortable just whacking in our own implementation for the sake of pushing this forwards, especially if it's something `adlfs` could fix quickly.

>In general, I think pangeo-forge bakeries should disable all of fsspec's caching on the write side. I'll try to write that up as an issue.

Is this something we can do easily? How would I do that?

**Comment by TomAugspurger** [comment] 2021-05-21 11:43
I think the fsspec docs describe the caching.

The latest issue I opened in adlfs has one of the problems I ran into in adlfs with caching disabled.

________________________________

**Comment by ciaranevans** [comment] 2021-05-21 14:09
@TomAugspurger is that:

```
use_listings_cache=False,
skip_instance_cache=True,
```

These? Should I add these in and try again?

**Comment by TomAugspurger** [comment] 2021-05-21 14:13
Perhaps, though https://github.com/dask/adlfs/issues/230 would likely need to be fixed first.

**Comment by ciaranevans** [comment] 2021-06-07 10:08
Just updating to point to this flow https://github.com/pangeo-forge/pangeo-forge-azure-bakery/blob/main/flow_test/oisst_recipe.py as this is the 'new' Recipe -> Flow conversion format and we're still getting the failures

**Closed** 2021-08-19 20:23 UTC
